@startuml

class Book {
-String isbn // partition key
-String title
-String author
-int yearPublished
-int lengthInPages
-ENUM genre
-List<Review> reviews
-String UUID
 }

 class TVShow {
-String title // partition key
-List<String> mainActors
-int lengthInSeasons
-int lengthInMinutes
-ENUM genre
-ENUM streamingService
-List<Review> reviews
-String UUID
}

class Movie {
-String title // partition key
-String director // sort key
-List<String> mainActors
-int lengthInMinutes
-ENUM genre
-ENUM streamingService
-List<Review> reviews
-String UUID
}

class Review {
-String userId // sort key
-String review
-int rating
-String UUIDOfEntity
}

class User {
-String userId // partition key
-String name
-Set<Book> toReadList
-Set<Book> currentlyReading
-Set<Book> readList
-Set<T> toWatchList
-Set<T> currentlyWatching
-Set<T> watchedList
}

newpage
class getBookActivity {}
class getBookRequest {}
class getBookResult {}

class getTVShowActivity {}
class getTVShowRequest {}
class getTVShowResult {}

class getMovieActivity {}
class getMovieRequest {}
class getMovieResult {}

class addBookToToReadListActivity {}
class addBookToToReadListRequest {}
class addBookToToReadListResult {}

class addBookToReadListActivity {}
class addBookToReadListRequest {}
class addBookToReadListResult{}

class addToToWatchListActivity {}
class addToToWatchListRequest {}
class addToToWatchListResult {}

class addToWatchedListActivity {}
class addToWatchedListRequest {}
class addToWatchedListResult {}

class addToCurrentlyWatchingListActivity {}
class addToCurrentlyWatchingListRequest {}
class addToCurrentlyWatchingListResult {}

class addToCurrentlyReadingListActivity {}
class addToCurrentlyReadingListRequest {}
class addToCurrentlyReadingListResult {}

class getToReadListActivity {}
class getToReadListRequest {}
class getToReadListResult {}

class getReadListActivity {}
class getReadListRequest {}
class getReadListResult {}

class getToWatchListActivity {}
class getToWatchListRequest {}
class getToWatchListResult {}

class getWatchedListActivity {}
class getWatchedListRequest {}
class getWatchedListResult {}

class getCurrentlyWatchingListActivity {}
class getCurrentlyWatchingRequest {}
class getCurrentlyWatchingResult {}

class getCurrentlyReadingListActivity {}
class getCurrentlyReadingRequest {}
class getCurrentlyReadingResult {}

class searchBookActivity {}
class searchBookRequest {}
class searchBookResult {}

class searchTVShowActivity {}
class searchTVShowRequest {}
class searchTVShowResult {}

class searchMovieActivity {}
class searchMovieRequest {}
class searchMovieResult {}

class removeBookFromToReadListActivity {}
class removeBookFromToReadListRequest {}
class removeBookFromToReadListResult {}

class removeFromToWatchListActivity {}
class removeFromToWatchListRequest {}
class removeFromToWatchListResult {}

class removeBookFromCurrentlyReadingListActivity {}
class removeBookFromCurrentlyReadingRequest {}
class removeBookFromCurrentlyReadingResult {}

class removeFromCurrentlyWatchingListActivity {}
class removeFromCurrentlyWatchingListRequest {}
class removeFromCurrentlyWatchingListResult {}

class createReviewRequest {}
class createReviewResult {}
class createReviewActivity {}

class addBookReviewActivity {}
class addBookReviewRequest {}
class addBookReviewResult {}

class addTVShowReviewActivity {}
class addTVShowReviewRequest {}
class addTvShowReviewResult {}

class addMovieReviewActivity {}
class addMovieReviewRequest {}
class addMovieReviewResult {}

class updateUserActivity {}
class updateUserRequest {}
class updateUserResult {}

newpage
class BookDao {}
class MovieDao {}
class TVShowDao{}
class ReviewDao{}
class UserDao{}
class ModelConverter{}
class ServiceComponent {}
class MetricsModule{}
class DaoModule{}
class BookNotFoundException {}
class TVShowNotFoundException {}
class MovieNotFoundException {}
class UserNotFoundException {}
class BookModel {}
class TVShowModel{}
class MovieModel{}
class UserModel {}
class ReviewModel {}
class AuthenticatedLambdaRequest{}
class LambdaActivityRunner{}
class LambdaRequest{}
class LambdaResponse{}
class getBookLambda {}
class getTVShowLambda  {}
class getMovieLambda  {}
class addBookToToReadListLambda  {}
class addBookToReadListLambda  {}
class addToToWatchListLambda  {}
class addToWatchedListLambda  {}
class addToCurrentlyWatchingListLambda  {}
class addToCurrentlyReadingListLambda  {}
class getToReadListLambda  {}
class getReadListLambda  {}
class getToWatchListLambda  {}
class getWatchedListLambda  {}
class getCurrentlyWatchingListLambda  {}
class getCurrentlyReadingListLambda  {}
class searchBookLambda  {}
class searchTVShowLambda  {}
class searchMovieLambda  {}
class removeBookFromToReadListLambda  {}
class removeFromToWatchListLambda  {}
class removeBookFromCurrentlyReadingListLambda  {}
class removeFromCurrentlyWatchingListLambda  {}
class createReviewLambda  {}
class addBookReviewLambda  {}
class addTVShowReviewLambda  {}
class addMovieReviewLambda  {}
class updateUserLambda  {}


enum GENRE {
GENRE.ROMANCE
GENRE.COMEDY
GENRE.HORROR
GENRE.SCIENCE_FICTION
GENRE.NONFICTION
GENRE.DOCUMENTARY
}


@enduml